#ifndef INIS_CONFIG_DEF_H
#define INIS_CONFIG_DEF_H

#define INIS_ENABLE_OPACITY 0
#define INIS_ENABLE_ANIMATIONS 0
#define INIS_ENABLE_SHADOWS 0
#define INIS_ENABLE_BLUR 0
#define INIS_ENABLE_XWAYLAND 0
#define INIS_ENABLE_IPC 1

#define INIS_DEFAULT_TERMINAL "kitty"
#define INIS_DEFAULT_MENU "rofi -show drun"
#define INIS_DEFAULT_FILE_MANAGER "thunar"
#define INIS_DEFAULT_BORDER_SIZE 2
#define INIS_DEFAULT_GAPS_IN 4
#define INIS_DEFAULT_GAPS_OUT 8
#define INIS_DEFAULT_MASTER_RATIO 0.55

#endif
